version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - /home/kmacquet/data/wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    depends_on: 
      - mariadb
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - /home/kmacquet/data/wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - /home/kmacquet/data/mysql:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
