version: '3.8'

services:
  db:
    restart: always
    container_name: "db"
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /Users/kmacquet/desktop/cursus42/inception/data/db:/var/lib/mysql

  wordpress:
    restart: always
    container_name: "wordpress"
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
      - nginx
      - db
    ports:
      - 8080:80
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - /Users/kmacquet/desktop/cursus42/inception/data/db:/var/www/html

  nginx:
    restart: always
    container_name: "nginx"
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    volumes:
      - /Users/kmacquet/desktop/cursus42/inception/data/wordpress:/var/www/html
