version: '3.0'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - ../Data/wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    environment:
      WORDPRESS_HOST: ${WORDPRESS_HOST}
      WORDPRESS_NAME: ${WORDPRESS_NAME}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
    restart: on-failure
    volumes:
      - ../Data/wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - ../Data/mysql:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

# volumes:
#   wordpress:
#     driver_opts:
#       type: "local"
#       o: bind
#       device: "../Data/wordpress"