version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    image: nginx
    ports:
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    restart: on-failure
    volumes:
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - v_mysql:/var/lib/mysql
    networks:
      - inception
  redis:
    container_name: redis
    build: requirements/redis/.
    image: redis
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    volumes:
      - v_mysql:/var/lib/mysql
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  vsftpd:
    container_name: vsftpd
    build: requirements/vsftpd/.
    image: vsftpd
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "21:21"
    restart: on-failure
    volumes:
      - v_wordpress:/home/${FTP_USER}
    networks:
      - inception
  grafana:
    container_name: grafana
    build: requirements/grafana/.
    image: grafana
    depends_on: 
      - wordpress
    environment: 
      - GF_SECURITY_ADMIN_USER=gfuser
      - GF_SECURITY_ADMIN_USER=gfpass
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - v_grafana:/var/lib/grafana
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  v_mysql:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/kmacquet/data/mysql'
  v_wordpress:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/kmacquet/data/wordpress'
  v_grafana:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/kmacquet/data/grafana'
    