version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    restart: on-failure
    volumes:
      - v_wordpress:/var/www/localhost/wordpress
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    volumes:
      - v_mysql:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  v_mysql:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/kmacquet/data/mysql'
  v_wordpress:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/kmacquet/data/wordpress'
    